services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
volumes:
  jenkins-data:

networks:
  jenkins:
    driver: bridge
